name:                mongo-test
version:             0.1.0.0
github:              "dbalseiro/mongo-test"
license:             BSD3
author:              "Diego Balseiro"
maintainer:          "dbalseiro@stackbuilders.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbalseiro/mongo-test#readme>

dependencies:
- base >= 4.7 && < 5
- data-default
- mongoDB
- mtl
- network
- text

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  mongo-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mongo-test

tests:
  mongo-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mongo-test
