name:                mongo-test
version:             0.1.0.0
github:              "dbalseiro/mongo-test"
license:             BSD3
author:              "Diego Balseiro"
maintainer:          "dbalseiro@stackbuilders.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Minimal project to prove the error
# category:            Web

description:         Please see the README on GitHub at <https://github.com/dbalseiro/mongo-test#readme>

dependencies:
- base >= 4.7 && < 5
- data-default
- mongoDB
- mtl
- network
- text

ghc-options:
- -Wall

executables:
  mongo-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
